# Group By() and Aggregating

# Create a Dataframe in pandas

In [85]:
import numpy as np
import pandas as pd

In [86]:


df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Employee": ["A", "B", "C", "D", "E"],
    "Salary": [50000, 60000, 40000, 45000, 55000]
})

print(df)

  Department Employee  Salary
0         IT        A   50000
1         IT        B   60000
2         HR        C   40000
3         HR        D   45000
4      Sales        E   55000

In [87]:
df.groupby("Department")["Salary"].median()

Department
HR       42500.0
IT       55000.0
Sales    55000.0
Name: Salary, dtype: float64

# Group By

# load a csv file

In [88]:
df = pd.read_csv('Datasets/matches.csv')
df.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [89]:
# to create a DataFrame
pd.DataFrame(df).head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [90]:
df.groupby('season')

In [91]:
df.groupby('season')['win_by_runs'].mean()
# df.groupby('season')['win_by_runs'].median()
# df.groupby('season')['win_by_runs'].sum()
# df.groupby('season')['win_by_runs'].count()
# df.groupby('season')['win_by_runs'].size()
# df.groupby('season')['win_by_runs'].min()
# df.groupby('season')['win_by_runs'].max()
# df.groupby('season')['win_by_runs'].std()
# df.groupby('season')['win_by_runs'].var()

season
2008    12.155172
2009    13.403509
2010    16.266667
2011    15.041096
2012    12.972973
2013    16.328947
2014    10.733333
2015    14.406780
2016    11.266667
2017    13.355932
Name: win_by_runs, dtype: float64

In [92]:
df.groupby('season')['win_by_runs'].sum().reset_index()

   season  win_by_runs
0    2008          705
1    2009          764
2    2010          976
3    2011         1098
4    2012          960
5    2013         1241
6    2014          644
7    2015          850
8    2016          676
9    2017          788

In [100]:
#  add a new columns in the end
df["Avg_runs"] = df.groupby('season')['win_by_runs'].transform('mean')
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,Avg_runs
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,13.355932
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,13.355932
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,13.355932
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,13.355932
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,13.355932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN,11.266667
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN,11.266667
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN,11.266667
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN,11.266667
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN,11.266667

# conditions

In [104]:
df["Avg_runs"] = (
    df.groupby("season")["win_by_runs"]
      .transform("mean")
)

In [112]:
df["Above_Avg"] = df["win_by_runs"] > df["Avg_runs"]
df["Above_Avg"]

0       True
1      False
2      False
3      False
4       True
       ...
631    False
632    False
633     True
634    False
635    False
Name: Above_Avg, Length: 636, dtype: bool

In [119]:
df[['season','winner','win_by_runs','Avg_runs','Above_Avg']]

     season                       winner  win_by_runs   Avg_runs  Above_Avg
0      2017          Sunrisers Hyderabad           35  13.355932       True
1      2017       Rising Pune Supergiant            0  13.355932      False
2      2017        Kolkata Knight Riders            0  13.355932      False
3      2017              Kings XI Punjab            0  13.355932      False
4      2017  Royal Challengers Bangalore           15  13.355932       True
..      ...                          ...          ...        ...        ...
631    2016  Royal Challengers Bangalore            0  11.266667      False
632    2016  Royal Challengers Bangalore            0  11.266667      False
633    2016          Sunrisers Hyderabad           22  11.266667       True
634    2016          Sunrisers Hyderabad            0  11.266667      False
635    2016          Sunrisers Hyderabad            8  11.266667      False

[636 rows x 5 columns]